name: app_radical_5_telas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  device_preview: any
  shared_preferences: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  get_it: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wyvernlogo.png
