// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgeiGRmye8euY093lFKxp08SJqC4zMKt4',
    appId: '1:233766981104:web:114b714534c5eb629f6135',
    messagingSenderId: '233766981104',
    projectId: 'cesar-manha-prog-disp-moveis',
    authDomain: 'cesar-manha-prog-disp-moveis.firebaseapp.com',
    storageBucket: 'cesar-manha-prog-disp-moveis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5RfgaHlo3uI1JqV5NZHnpcISB0GF3ZjQ',
    appId: '1:233766981104:android:a68e29944f4808499f6135',
    messagingSenderId: '233766981104',
    projectId: 'cesar-manha-prog-disp-moveis',
    storageBucket: 'cesar-manha-prog-disp-moveis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPcv3XSW8KAWKGqDMCW7EMEBtK-mapud8',
    appId: '1:233766981104:ios:fdcf9c8c083423599f6135',
    messagingSenderId: '233766981104',
    projectId: 'cesar-manha-prog-disp-moveis',
    storageBucket: 'cesar-manha-prog-disp-moveis.firebasestorage.app',
    iosBundleId: 'com.example.appRadical5Telas',
  );
}
